One program identifier
bpfd-dev/bpfd pull request #701
Opened 2023-09-12 03:34 UTC by astoycos

closes #656 

Fixes #580

TODO (add notes mark as ready for review)

2023-09-12 15:56 UTC, astoycos commented
There's still some small spelling and nit stuff in comments but otherwise this should be read for review

2023-09-13 16:00 UTC, astoycos commented
Added an extra commit here that fixes filtering by metadata + adds an integration test to ensure it's working.

2023-09-13 16:45 UTC, dave-tucker requested changes

2023-09-13 16:45 UTC, dave-tucker commented on bpfd/src/bpf.rs
>          })
Use `values_mut()`

```suggestion
        self.programs.values_mut().filter(|p| {
```

2023-09-13 16:46 UTC, dave-tucker requested changes
A few nits but overall looking good. I haven't reviewed the Go code though.

2023-09-13 16:46 UTC, dave-tucker requested changes
A few nits but overall looking good. I haven't reviewed the Go code though.

2023-09-13 19:52 UTC, astoycos commented on bpfd/src/bpf.rs
>              })
Arg good catch thanks!

2023-09-14 07:53 UTC, dave-tucker approved these changes

2023-09-14 13:35 UTC, Billy99 commented on bpfd/src/bpf.rs
> +            Some(id) => {
```suggestion
            Some(owner_id) => {
```
`id` already exists and needs to be used in this case statement. Change `id` to something else in this case statement.

2023-09-14 13:35 UTC, Billy99 commented on bpfd/src/bpf.rs
> +                    map.used_by.push(id);
Except here. Need to add this program's `id` to the map owner's used_by list.

2023-09-14 13:35 UTC, Billy99 commented on bpfd/src/bpf.rs
> +                if let Some(map) = self.maps.get_mut(&id) {
```suggestion
                if let Some(map) = self.maps.get_mut(&owner_id) {
```

2023-09-14 13:35 UTC, Billy99 commented on bpfd/src/bpf.rs
> +                    if let Some(program) = self.programs.get_mut(&id) {
Now `program.data.used_by` is what is returned in list/get, so this `if` block needs to be in a loop, and all programs with an instance in this `map.used_by` need to be updated with this new `id`.

The same will need to be done when a program in the `map.used_by` is unloaded. Also, `program.data.used_by` is not being updated on a bpfd restart.

The problem is you are trying to keep the same data in two different places and now you have to keep them in sync. And its a many `program.data.used_by` to one `map.used_by`. It's probably best to not keep `used_by` in ProgramData.

2023-09-14 13:36 UTC, merged

2023-09-14 15:22 UTC, astoycos commented on bpfctl/src/main.rs
> +    name: String,
Nope, literally just the name