bpfd-operator: Make the CSI deployment default for bpfd-operator
bpfd-dev/bpfd pull request #811
Opened 2023-11-08 21:19 UTC by Billy99

Support for implementing the Container Storage Interface Specification is already inplace. Update the deployment to use it by default and modify the examples to use it as well. Doumentation also needs to be updated.

Fixes: #776

2023-11-16 16:47 UTC, Billy99 commented
@astoycos Ready for review.

/hold
Adding a hold so that it doesn't merge until I remove the first commit (`[DO NOT MERGE] Use updated examples from private repo`)

2023-11-16 20:04 UTC, astoycos requested changes
OK @Billy99 This generally looks good just a few things! 

- We don't need to maintain a no-csi deployment, from a K8s POV the user shouldn't even know we're making use of that :) 

- Please remove the maps field from the `bpfProgram` CRD since we no longer populate it anyways (so that the bpfd-agent can be unpriviledged) https://github.com/bpfd-dev/bpfd/blob/main/bpfd-operator/apis/v1alpha1/bpfprogram_types.go#L49.  Eventually maps will be replaced with another CRD but the owner reference for that will be the parent *Program not the node level BpfProgram

- In the bpfd-operator helpers file please remove the get_maps function AND remove all of the commented out code there I don't think we need those anymore.

2023-11-16 20:08 UTC, Billy99 commented on bpfd-operator/config/bpfd-deployment/daemonset-no-csi.yaml
>            readOnly: true
So my only thought here was with CSI we are forced to use K8s v1.26 or higher. So this allows bpfd to run on older versions of K8s.

2023-11-16 21:23 UTC, Billy99 commented on bpfd-operator/Makefile
> +## Default deploy target is KIND based without CSI driver initialized.
Done

2023-11-16 21:23 UTC, Billy99 commented on bpfd-operator/Containerfile.bpfd-operator
> +COPY --from=bpfd-operator-build /usr/src/bpfd/bpfd-operator/config/bpfd-deployment/daemonset-no-csi.yaml ./config/bpfd-deployment/daemonset-no-csi.yaml
Done

2023-11-16 21:23 UTC, Billy99 commented on bpfd-operator/pkg/helpers/helpers.go
> +func GetMaps(c *bpfdclientset.Clientset, ProgramName string, mapPinPath string, mapNames []string) (map[string]string, error) {
Done

2023-11-16 21:23 UTC, Billy99 commented on bpfd-operator/internal/constants.go
> +	BpfdDaemonNoCsiManifestPath = "./config/bpfd-deployment/daemonset-no-csi.yaml"
Done

2023-11-16 21:24 UTC, Billy99 commented on bpfd-operator/controllers/bpfd-operator/configmap.go
> +	BpfdNoCsiDeployment    string
Done

2023-11-16 21:24 UTC, Billy99 commented on bpfd-operator/config/bpfd-deployment/daemonset-no-csi.yaml
>            readOnly: true
Done

2023-11-17 03:22 UTC, Billy99 commented
@astoycos I think I addressed all your comments and CI is Green. When you are happy with it, I'll remove the first commit.

2023-11-17 03:30 UTC, astoycos approved these changes
LGTM

Thanks @Billy99!!!

2023-11-17 03:35 UTC, merged